---

csr1:
  hostname: 172.31.33.240
  groups:
    - ios
    - csr_routers
    - site1

csr2:
  hostname: 172.31.33.241
  groups:
    - ios
    - csr_routers
    - site2

mx3:
  hostname: 172.31.33.242
  groups:
    - junos
    - mx_routers
    - site1

mx4:
  hostname: 172.31.33.243
  groups:
    - junos
    - mx_routers
    - site2
